const { createTerm, generateSearchTerms } = require('./terms');
const { combinations } = require('./cartesian');
const stringify = require('csv-stringify');
const fs = require('fs');

const locations = [
  'India',
  'Bhubaneshwar',
  'Odisha',
  'Kolkata, West Bengal',
  'VISAK, Andhra Pradesh',
  'Chennai, Tamilnadu',
  'Hyderabad, Telengana',
  'Delhi',
  'Ahmedabad, Gujurat',
  'Pune, Maharashtra',
  'Bangalore, Karnataka',
  'Mumbai, Maharastra',
  'Warangal, Andhra Pradesh',
  'Luchknow, Uttar Pradesh',
  'Thiruanantapuram, Kerla',
  'Qatar',
  'Africa',
  'South Africa',
  'Kenya',
  'Nigeria',
  'Dubai',
  'Bahrain',
  'Abu Dhabi',
  'Bangladesh',
  'Ireland',
  'Europe',
  'Canada',
  'USA',
  'UK',
  'UAE',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Vietnam',
  'Australia',
  'Estonia',
  'Saudi',
  'Mauritius',
  'Tanzania',
  'France',
  'Spain',
  'Italy',
  'Kuwait',
  'Afganisthan',
  'North East',
  'Chandigarh',
];

let topics = [
  createTerm('Cyber Security', {
    exact: [
      'cyber security audit company',
      'cyber security testing company',
      'cyber security firm',
      'top cyber security firm',
      'best cyber security company',
      'top 10 cyber security companies',
      'cyber security service providers',
      'cyber security consulting services',
      'cyber security consultancy',
      'cyber security consulting company',
      'cyber security consulting firm',
      'biggest cyber security company',
      'biggest cyber security firm',
      'cyber security auditing services',
      'cyber security assessment company',
      'cyber security companies',
      'cyber security providers',
      'top cyber security audit firm',
      'best cyber security testing company',
      'top 10 biggest cyber security consulting companies',
      'No.1 cyber security assessment firm',
    ],
  }),
  createTerm('CERT-IN Cyber Security Audit', {
    exact: [
      'CERT-IN Cyber Security Audit company',
      'CERT-IN Cyber Security Audit testing company',
      'CERT-IN Cyber Security Audit firm',
      'top CERT-IN Cyber Security Audit firm',
      'best CERT-IN Cyber Security company',
      'top 10 CERT-IN Cyber Security Audit companies',
      'CERT-IN Cyber Security Audit service providers',
      'CERT-IN Cyber Security consultancy',
      'CERT-IN Cyber Security consulting company',
      'CERT-IN Cyber Security consulting services',
      'CERT-IN Cyber Security Audit consulting firm',
      'biggest CERT-IN Cyber Security Audit company',
      'largest CERT-IN Cyber Security Audit firm',
      'CERT-IN Cyber Security Audit auditing services',
      'CERT-IN Cyber Security assessment company',
      'CERT-IN Cyber Security Audit companies',
      'CERT-IN Cyber Security Audit providers',
      'top CERT-IN Cyber Security Audit firm',
      'best CERT-IN Cyber Security Audit testing company',
      'top 10 biggest CERT-IN Cyber Security Audit consulting companies',
      'No.1 CERT-IN Cyber Security assessment firm',
    ],
  }),
  createTerm('ISO Compliance', {
    exact: [
      'iso compliance certificate',
      'iso certification provider',
      'best iso compliance consultancy',
      'top iso compliance service provider',
      'trusted iso compliance certification provider',
      'top iso compliance audit firm',
      'biggest iso compliance management service provider',
      'top iso compliance audit provider',
      'biggest iso compliance auditing company',
      'top 10 iso compliance audit company',
      'iso compliance consultant',
      'best iso compliance cyber security auditing company',
      'iso compliance cyber security company',
      'who provide iso compliance in cyber security',
      'top 10 iso compliance assessment firms',
      'iso compliance auditing service providers',
      'iso internal audit compliance auditing company',
      'iso 27001 compliance cyber security firm',
      'top 10 iso 27001 compliance auditing company',
      'No.1 iso 27001 information security auditing firm',
      'iso 27001 compliance security testing company',
      'iso standard 27001 compliance assessment company',
    ],
  }),
  createTerm('PCI DSS Compliance', {
    exact: [
      'pci dss compliance certificate',
      'iso certification provider',
      'best pci dss compliance consultancy',
      'top pci dss compliance service provider',
      'trusted pci dss compliance certification provider',
      'top pci dss compliance audit firm',
      'biggest pci dss compliance management service provider',
      'top pci dss compliance audit provider',
      'biggest pci dss compliance auditing company',
      'top 10 pci dss compliance audit company',
      'pci dss compliance consultant',
      'pci compliance cyber security auditing company',
      'pci dss compliance cyber security company',
      'who provide pci dss compliance in cyber security',
      'top 10 pci dss compliance assessment firms',
      'pci dss compliance auditing service providers',
      'pci dss internal compliance audit auditing company',
      'pci dss compliance cyber security firm',
      'top 10 payment card industry dss compliance auditing company',
      'No.1 pci dss compliance information security auditing firm',
      'pci dss compliance security testing company',
      'payment card industry data security standard compliance audit company',
      'pci data security standard auditing services',
    ],
  }),
  createTerm('SOC Compliance', {
    exact: [
      'system and organization controls auditing firm',
      'soc compliance company',
      'soc compliance testing company',
      'soc compliance firm',
      'top soc compliance firm',
      'best soc cyber security company',
      'top 10 soc compliance companies',
      'soc compliance service providers',
      'soc compliance consultancy',
      'soc compliance consulting company',
      'soc compliance consulting firm',
      'biggest soc1 and soc2 compliance company',
      'biggest soc compliance firm',
      'soc compliance auditing services',
      'soc compliance cyber security auditing company',
      'best soc compliance assessment company',
      'top 10 soc compliance companies',
      'best soc compliance providers',
      'top soc compliance firm',
      'best soc compliance testing company',
      'top 10 biggest soc compliance consulting companies',
      'No.1 soc compliance assessment firm',
      'soc compliance internal auditing services',
      'soc1 and soc2 internal audit company',
    ],
  }),
  createTerm('HIPAA Compliance', {
    exact: [
      'health insurance portability and accountability act auditing firm',
      'hipaa compliance company',
      'hipaa compliance testing company',
      'hipaa compliance firm',
      'top hipaa compliance firm',
      'best hipaa compliance cyber security company',
      'top 10 hipaa compliance companies',
      'hipaa compliance service providers',
      'hipaa compliance consultancy',
      'hipaa compliance consulting company',
      'hipaa compliance consulting firm',
      'biggest hipaa compliance company',
      'biggest hipaa compliance firm',
      'hipaa compliance auditing services',
      'hipaa compliance cyber security auditing company',
      'best hipaa compliance assessment company',
      'top 10 hipaa compliance companies',
      'best hipaa compliance providers',
      'top hipaa compliance firm',
      'best hipaa compliance testing company',
      'top 10 biggest hipaa compliance consulting companies',
      'No.1 hipaa compliance assessment firm',
      'hipaa compliance internal auditing services',
      'hipaa compliance internal audit company',
    ],
  }),
  createTerm('GDPR Compliance', {
    exact: [
      'General Data Protection Regulation auditing firm',
      'gdpr compliance company',
      'gdpr compliance testing company',
      'gdpr compliance firm',
      'top gdpr compliance firm',
      'best gdpr compliance cyber security company',
      'top 10 gdpr compliance companies',
      'top data protection firm',
      'best data protection and cyber security audit company',
      'gdpr compliance service providers',
      'gdpr compliance consultancy',
      'gdpr compliance consulting company',
      'gdpr compliance consulting firm',
      'biggest gdpr compliance company',
      'biggest gdpr compliance firm',
      'gdpr compliance auditing services',
      'gdpr compliance cyber security auditing company',
      'best gdpr compliance assessment company',
      'top 10 gdpr compliance companies',
      'best gdpr compliance providers',
      'top gdpr compliance firm',
      'best gdpr compliance testing company',
      'top 10 biggest gdpr compliance consulting companies',
      'No.1 gdpr compliance assessment firm',
      'gdpr compliance internal auditing services',
      'gdpr compliance internal audit company',
    ],
  }),
  createTerm('FISMA Compliance', {
    exact: [
      'federal information security management act compliance auditing firm',
      'fisma compliance company',
      'fisma compliance testing company',
      'fisma compliance firm',
      'top fisma compliance firm',
      'best fisma compliance cyber security company',
      'top 10 fisma compliance companies',
      'top information security audit firm',
      'best data protection and information security audit company',
      'fisma compliance service providers',
      'fisma compliance consultancy',
      'fisma compliance consulting company',
      'fisma compliance consulting firm',
      'biggest fisma compliance company',
      'biggest fisma compliance firm',
      'fisma compliance auditing services',
      'best fisma compliance assessment company',
      'fisma compliance cyber security auditing company',
      'top 10 fisma compliance companies',
      'best fisma compliance providers',
      'top fisma compliance firm',
      'best fisma compliance testing company',
      'top 10 biggest fisma compliance consulting companies',
      'No.1 fisma compliance assessment firm',
      'fisma compliance internal auditing services',
      'fisma compliance internal audit company',
    ],
  }),
  createTerm('GRC Compliance', {
    exact: [
      'governance risk and compliance auditing firm',
      'grc compliance company',
      'grc compliance testing company',
      'grc compliance firm',
      'top grc compliance firm',
      'best grc compliance cyber security company',
      'top 10 grc compliance companies',
      'top grc compliance testing firm',
      'best governance risk compliance audit company',
      'grc compliance service providers',
      'grc compliance consultancy',
      'grc compliance consulting company',
      'grc compliance consulting firm',
      'biggest grc compliance company',
      'biggest grc compliance firm',
      'grc compliance auditing services',
      'best grc compliance assessment company',
      'top 10 grc compliance companies',
      'best grc compliance providers',
      'top grc compliance firm',
      'grc compliance cyber security auditing company',
      'best grc compliance testing company',
      'top 10 biggest grc compliance consulting companies',
      'No.1 grc compliance assessment firm',
      'grc compliance internal auditing services',
      'grc compliance internal audit company',
    ],
  }),
];

const baseTerms = topics.map((term) => {
  return generateSearchTerms(term);
});

let totalSearchTerms = 0;
baseTerms.forEach((term) => {
  const title = term.title;
  const searchTerms = term.terms;
  const stringifier = stringify({
    delimiter: ',',
  });
  // Add number of terms to the total.
  const count = searchTerms.length * locations.length;
  totalSearchTerms += count;
  // Headers
  stringifier.write(['Topic:', title]);
  stringifier.write([
    'Total terms generated',
    count,
    '',
    'Total final keywords',
    searchTerms.length,
    '',
    'Sub-terms',
    locations.length,
  ]);
  stringifier.write(['Keywords']);
  stringifier.write(searchTerms);

  locations.forEach((x) => {
    let result = null;
    result = combinations(searchTerms, ['in'], [x]).map((x) => x.join(' '));
    stringifier.write(result);

    return result;
  });
  let stream = fs.createWriteStream(`./output/${title}.csv`);
  stringifier.pipe(stream);
});
console.log(`* Total search terms generated: ${totalSearchTerms}`);
